sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jbsolanki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbsolanki/react-test npm run test

after_success:
  - docker build -t jbsolanki/multi-client-10-14 ./client
  - docker build -t jbsolanki/multi-nginx-10-14 ./nginx
  - docker build -t jbsolanki/multi-server-10-14 ./server
  - docker build -t jbsolanki/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jbsolanki/multi-client-10-14
  - docker push jbsolanki/multi-nginx-10-14
  - docker push jbsolanki/multi-server-10-14
  - docker push jbsolanki/multi-worker-10-14

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-ap-south-1-235308968417'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

