sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jbsolanki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbsolanki/react-test npm test

